language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
install: pip install -r requirements.txt
script: nosetests -v -w tests/  --with-cov --cov chatpy --cov-report term-missing
env:
  global:
  - secure: VmZrITJBKXz1muzsjmMdSX9eX+7rA9frGjXflo2U/KBsJmjvTTXx2RKWYN+UcYJ4IAXnFOq0nOkMjsexChq2Y+PtgnC9su0f69X1bwLU8HqBu795DTW7sWwANEimVjcpo9qdxgNDbTFHsm/gZ97TBr4+JYwk7A+RbD3rnJgaU/w=
